### ISSUE TITLE
Restructure Nansen-Cloud into more generic apps and reconsider the database

### ISSUE THREAD

**Issue by mortenwh** [nansencenter/nansen-cloud#7]
First of all, this requires clear definitions of the metadata to use in Nansat and Nansen-Cloud. Therefore, we have created the repository https://github.com/nansencenter/nersc-metadata

The branch issue has some initial efforts to accomplish the new structure as outlined in https://docs.google.com/drawings/d/1wQPPjK2BMRHhHYlnmYbdQrzn44qEvKbHoIhBFG8INvo/edit and https://docs.google.com/presentation/d/1nMIrBPZquxL7BA4-L5yRWjwpfgeJMx7ZKJFjXvbEdF4/edit#slide=id.ge0b03d2d7_0_16 - note that this is not well tested and may not function at the moment.

We must work on three tasks related to this issue:

1. Prepare metadata conventions in https://github.com/nansencenter/nersc-metadata
2. Solve nansencenter/nansat#120 in line with 1
3. Restructure nansencloud to use the standards defined in https://github.com/nansencenter/nersc-metadata

The models in nansen-cloud should contain standard fields and field values (e.g., some fields have only two or three optional values) defined in nansencenter/nersc-metadata, also used in nansat. The present layout of the catalog-app (https://docs.google.com/drawings/d/1wQPPjK2BMRHhHYlnmYbdQrzn44qEvKbHoIhBFG8INvo) needs to be checked and discussed further.

**Comment by mortenwh** [comment]
In the DIF standard, one of the required terms is “Parameters (Science Keywords)”. This can be interpreted as, e.g., sigma0 in VV polarization (?). Presently in nansencloud.catalog, we have the Product model, which resembles the “Parameters” term in DIF but at the moment refers to png’s for web presentation. Should we rather use the DIF standard, listing the important scientific parameters under the “Parameters” term, and add a term “Ilustrations”/”Visualizations”, or something like that, to refer to the png’s or even animations? That would be more correct, wouldn’t it? It means changing Product to Parameter, and add a class Visualization.

When processing SAR data we need to do noise removal and add some extra bands by combination of existing ones, e.g., in quad-polarization we add PR, NP, PD, and CP bands. Therefore, we should process the files with a general SAR processing software, export to netcdf, and then add the netcdf as a datalocation (perhaps the name of the DataLocation class could be changed to Product), then adding the derived parameters to the Dataset instance (it is a waste to have more than one dataset covering the exact same time and region, so better then to have parameters that are stored at given datalocations).

So change “Product” to “Parameter”, add a class “Visualization” and change “DataLocation” to “Product”? See https://docs.google.com/drawings/d/1wQPPjK2BMRHhHYlnmYbdQrzn44qEvKbHoIhBFG8INvo/edit 

Storage of derived parameters (e.g. sar wind) should be done in netcdf’s (products) so they are available for later analysis. Then these parameters should also be visualized and the visualizations should be separate products (e.g. png files)). The actual paths (also downloads) are defined in settings.py, which should be different in production and development.

Then we need to make ingestor commands for data that cannot be opened with nansat as well. Perhaps the command “ingest” should be changed to “ingest_nansat”.

**Comment by akorosov** [comment]
Kinda disagree. The simplest solution is to not consider adding a new Dataset as a waste. Then that's the meaning of the current fields (whatever you call them) without major changes:
Dataset - a file (or stream) with data (either original N1 or generated ncetcdf)
Product - visualization of one of the products (e.g. PNG overlay)
DataLocation - where is the actual data

It fits perfectly processing SAR.
1. Ingest N1 file as a new Dataset and add DataLocation pointing to N1 file
2. Process generate two files: netcdf with data, png with quicklook
3. Ingest 'netcdf with data' as a new Dataset and add DataLocation pointing to netcdf file
4. Add Product which has standard_name refering to the generated PNG quicklook and add DataLocation pointing to PNG file on the web

**Comment by mortenwh** [comment]
See https://docs.google.com/document/d/1GINZJcrvYrudVIO6-MQ-x3doOr0W7YdK_HPBDcDh4Lc/edit
and https://docs.google.com/document/d/1GINZJcrvYrudVIO6-MQ-x3doOr0W7YdK_HPBDcDh4Lc/edit

```Product``` -> ```Parameter```
```Visualization``` added (with uri- or file-field to specify its location)
```DataLocation```-> ```DatasetLocation```

Point list in @akorosov's comment:

1. ok
2. The netcdf will be a new dataset with a ```DatasetLocation_set``` (uri's) and the png will be a ```Visualization``` of one or more parameters (e.g., bands in nansat)
3. ok
4. Add ```DatasetParameter``` that links a dataset with a standard ```Parameter``` (CF and gcmd compliant) (the png ```Visualization``` will point to ```DatasetParameter```)


The Parameter model should reflect the CF variables and gcmd science keywords.

This is a rather big change - so new issue branch started...

**Comment by mortenwh** [comment]
Updates in https://docs.google.com/document/d/1Tcbyxc2KGSGojl0EaB3aYguQRTnoyrXennkqbISVDsA/edit

**Comment by mortenwh** [comment]
Done at 0461c0058da9b63a9b87155027dd34ae8b353c5d
